### ISSUE TITLE
[FaceDetailer] CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by VladM-N1** [ltdrdata/ComfyUI-Impact-Pack#1145]
Hi @ltdrdata 
I've issues with FaceDetailer
It's throwing
"CUDA error: no kernel image is available for execution on the device"

I don't see this error during "generating" images with KSampler

Affected versions:
* 8.24 (latest)
* 8.17

GPU: Nvidia 5070 Ti
  `python -c "import torch; print(torch.version.cuda)"` output: `12.9`

**Comment by VladM-N1** [comment]
I've tried to build sam2 locally by cloning it and installing with `pip install -e .`  - no luck with that

**Comment by ltdrdata** [comment]
Please upload the full log.

**Comment by VladM-N1** [comment]
```bash
[START] Security scan
[ComfyUI-Manager] Using uv as Python module for pip operations.
Using Python 3.12.12 environment at: /home/redacted/miniforge3
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-11-15 10:28:51.433
** Platform: Linux
** Python version: 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
** Python executable: /home/redacted/miniforge3/bin/python
** ComfyUI Path: /home/redacted/stable-diffusion/ComfyUI
** ComfyUI Base Folder Path: /home/redacted/stable-diffusion/ComfyUI
** User directory: /home/redacted/stable-diffusion/ComfyUI/user
** ComfyUI-Manager config path: /home/redacted/stable-diffusion/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /home/redacted/stable-diffusion/ComfyUI/user/comfyui.log
Using Python 3.12.12 environment at: /home/redacted/miniforge3
Using Python 3.12.12 environment at: /home/redacted/miniforge3

Prestartup times for custom nodes:
   0.4 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-manager

Checkpoint files will always be loaded safely.
Total VRAM 15818 MB, total RAM 31163 MB
pytorch version: 2.9.1+cu129
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 5070 Ti : cudaMallocAsync
Enabled pinned memory 29605.0
working around nvidia conv3d memory bug.
Using pytorch attention
Python version: 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
ComfyUI version: 0.3.68
ComfyUI frontend version: 1.28.8
[Prompt Server] web root: /home/redacted/miniforge3/lib/python3.12/site-packages/comfyui_frontend_package/static
### Loading: ComfyUI-Impact-Subpack (V1.3.5)
[Impact Pack/Subpack] Using folder_paths to determine whitelist path: /home/redacted/stable-diffusion/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[Impact Pack/Subpack] Ensured whitelist directory exists: /home/redacted/stable-diffusion/ComfyUI/user/default/ComfyUI-Impact-Subpack
[Impact Pack/Subpack] Loaded 0 model(s) from whitelist: /home/redacted/stable-diffusion/ComfyUI/user/default/ComfyUI-Impact-Subpack/model-whitelist.txt
[Impact Subpack] ultralytics_bbox: /home/redacted/stable-diffusion/ComfyUI/models/ultralytics/bbox
[Impact Subpack] ultralytics_segm: /home/redacted/stable-diffusion/ComfyUI/models/ultralytics/segm

[ReActor] - STATUS - Running v0.6.2-a4 in ComfyUI
Torch version: 2.9.1+cu129
### Loading: ComfyUI-Impact-Pack (V8.16.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V3.37.1)
[ComfyUI-Manager] network_mode: public
### ComfyUI Version: v0.3.68-27-g443056c4 | Released on '2025-11-14'

Import times for custom nodes:
   0.0 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-pack
   0.0 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-manager
   0.2 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-subpack
   0.9 seconds: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-reactor

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Context impl SQLiteImpl.
Will assume non-transactional DDL.
No target revision found.
Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH ComfyRegistry Data: 5/106
FETCH ComfyRegistry Data: 10/106
FETCH ComfyRegistry Data: 15/106
FETCH ComfyRegistry Data: 20/106
FETCH ComfyRegistry Data: 25/106
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/clipspace.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /extensions/core/groupNode.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/buttonGroup.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
[DEPRECATION WARNING] Detected import of deprecated legacy API: /scripts/ui/components/button.js. This is likely caused by a custom node extension using outdated APIs. Please update your extensions or contact the extension author for an updated version.
FETCH ComfyRegistry Data: 30/106
got prompt
[ReActor] 10:29:18 - STATUS - Checking for any unsafe content...
[ReActor] 10:29:19 - STATUS - Ensuring NSFW detection model exists...
[ReActor] 10:29:20 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 10:29:20 - STATUS - Analyzing Source Image...
[ReActor] 10:29:21 - STATUS - Analyzing Target Image...
[ReActor] 10:29:21 - STATUS - Swapping...
[ReActor] 10:29:21 - STATUS - --Done!--
FETCH ComfyRegistry Data: 35/106
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
Requested to load SDXLClipModel
loaded completely; 95367431640625005117571072.00 MB usable, 1560.80 MB loaded, full load: True
CLIP/text encoder model load device: cuda:0, offload device: cpu, current: cuda:0, dtype: torch.float16

!!! Exception during processing !!! CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/redacted/stable-diffusion/ComfyUI/execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "/home/redacted/stable-diffusion/ComfyUI/execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-pack/modules/impact/impact_pack.py", line 626, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-pack/modules/impact/impact_pack.py", line 558, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-subpack/modules/subcore.py", line 420, in detect
    detected_results = inference_bbox(self.bbox_model, utils.tensor2pil(image), threshold)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-impact-subpack/modules/subcore.py", line 326, in inference_bbox
    pred = model(image, conf=confidence, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 182, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 540, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 225, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 38, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 306, in stream_inference
    self.model.warmup(
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/nn/autobackend.py", line 881, in warmup
    non_max_suppression(warmup_boxes)  # warmup NMS
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/ultralytics/utils/nms.py", line 154, in non_max_suppression
    i = torchvision.ops.nms(boxes, scores, iou_thres)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/torchvision/ops/boxes.py", line 48, in nms
    return torch.ops.torchvision.nms(boxes, scores, iou_threshold)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/miniforge3/lib/python3.12/site-packages/torch/_ops.py", line 1255, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: no kernel image is available for execution on the device
Search for `cudaErrorNoKernelImageForDevice' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Prompt executed in 8.23 seconds
FETCH ComfyRegistry Data: 40/106
^C
Stopped server
Cannot connect to comfyregistry.
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json[ComfyUI-Manager] Due to a network error, switching to local mode.
=> custom-node-list.json
=> cannot schedule new futures after shutdown
FETCH DATA from: /home/redacted/stable-diffusion/ComfyUI/custom_nodes/comfyui-manager/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
[W1115 10:29:31.700893217 AllocatorConfig.cpp:28] Warning: PYTORCH_CUDA_ALLOC_CONF is deprecated, use PYTORCH_ALLOC_CONF instead (function operator())
```

**Comment by VladM-N1** [comment]
I think we can close this. It works now, it was CUDA version mismatch.
I've updated my system CUDA to 13.0 and re-installed torch+cu130 for it, re-installed packed - and it works
